kind: ConfigMap
apiVersion: v1
metadata:
  name: topolvm-operator-setting
  namespace: topolvm-system
data:
  KUBELET_ROOT_DIR: "/var/lib/kubelet"
  OPERATOR_LOG_LEVEL: "INFO"

  ENABLE_RAW_DEVICE: "false"
  ENABLE_TOPOLVM: "true"
  RAW_DEVICE_IMAGE: "build-harbor.alauda.cn/acp/raw-device:dev"
  TOPOLVM_IMAGE: "build-harbor.alauda.cn/acp/topolvm:v3.6.0"
  # Set replicas for csi provisioner deployment.
  CSI_PROVISIONER_REPLICAS: "2"

  CSI_LOG_LEVEL: "DEBUG"
  CSI_REGISTRAR_IMAGE: "build-harbor.alauda.cn/3rdparty/csi-node-driver-registrar:v2.0.1"
  CSI_RESIZER_IMAGE: "build-harbor.alauda.cn/3rdparty/csi-resizer:v1.0.1"
  CSI_PROVISIONER_IMAGE: "build-harbor.alauda.cn/3rdparty/csi-provisioner:test-3.0.0"
  CSI_SNAPSHOTTER_IMAGE: "build-harbor.alauda.cn/3rdparty/csi-snapshotter:v3.0.2"
  CSI_ATTACHER_IMAGE: "build-harbor.alauda.cn/3rdparty/csi-attacher:v2.1.0"
  CSI_LIVENESS_IMAGE: "build-harbor.alauda.cn/acp/k8scsi/livenessprobe:v2.1.0"


  CSI_PROVISIONER_TOLERATIONS: |
    - effect: NoSchedule
      key: node-role.kubernetes.io/controlplane
      operator: Exists
    - effect: NoExecute
      key: node-role.kubernetes.io/etcd
      operator: Exists
  CSI_PLUGIN_TOLERATIONS: |
    - effect: NoSchedule
      key: node-role.kubernetes.io/controlplane
      operator: Exists
    - effect: NoExecute
      key: node-role.kubernetes.io/etcd
      operator: Exists
  CSI_TOPOLVM_PROVISIONER_TOLERATIONS: |
    - operator: Exists
  CSI_TOPOLVM_PLUGIN_TOLERATIONS: |
    - operator: Exists
  CSI_RAW_DEVICE_PROVISIONER_TOLERATIONS: |
    - operator: Exists
  CSI_RAW_DEVICE_PLUGIN_TOLERATIONS: |
    - operator: Exists
  CSI_TOPOLVM_PROVISIONER_RESOURCE: |
   - name : csi-provisioner
     resource:
       requests:
         memory: 128Mi
         cpu: 100m
       limits:
         memory: 256Mi
         cpu: 200m
   - name : csi-resizer
     resource:
       requests:
         memory: 128Mi
         cpu: 100m
       limits:
         memory: 256Mi
         cpu: 200m
   - name : csi-attacher
     resource:
       requests:
         memory: 128Mi
         cpu: 100m
       limits:
         memory: 256Mi
         cpu: 200m
   - name : csi-snapshotter
     resource:
       requests:
         memory: 128Mi
         cpu: 100m
       limits:
         memory: 256Mi
         cpu: 200m
   - name : csi-topolvm-plugin
     resource:
       requests:
         memory: 512Mi
         cpu: 250m
       limits:
         memory: 1Gi
         cpu: 500m
   - name : c
     resource:
       requests:
         memory: 128Mi
         cpu: 50m
       limits:
         memory: 256Mi
         cpu: 100m
  CSI_TOPOLVM_PLUGIN_RESOURCE: |
   - name : driver-registrar
     resource:
       requests:
         memory: 128Mi
         cpu: 50m
       limits:
         memory: 256Mi
         cpu: 100m
   - name : csi-topolvm-plugin
     resource:
       requests:
         memory: 512Mi
         cpu: 250m
       limits:
         memory: 1Gi
         cpu: 500m
    - name : lvmd
      resource:
        requests:
          memory: 128Mi
          cpu: 50m
        limits:
          memory: 256Mi
          cpu: 100m
   - name : liveness-prometheus
     resource:
       requests:
         memory: 128Mi
         cpu: 50m
       limits:
         memory: 256Mi
         cpu: 100m
  CSI_RAW_DEVICE_PROVISIONER_RESOURCE: |
   - name : csi-provisioner
     resource:
       requests:
         memory: 128Mi
         cpu: 100m
       limits:
         memory: 256Mi
         cpu: 200m
   - name : csi-raw-device-plugin
     resource:
       requests:
         memory: 512Mi
         cpu: 250m
       limits:
         memory: 1Gi
         cpu: 500m
   - name : liveness-prometheus
     resource:
       requests:
         memory: 128Mi
         cpu: 50m
       limits:
         memory: 256Mi
         cpu: 100m
  CSI_RAW_DEVICE_PLUGIN_RESOURCE: |
   - name : driver-registrar
     resource:
       requests:
         memory: 128Mi
         cpu: 50m
       limits:
         memory: 256Mi
         cpu: 100m
   - name : csi-raw-device-plugin
     resource:
       requests:
         memory: 512Mi
         cpu: 250m
       limits:
         memory: 1Gi
         cpu: 500m
   - name : liveness-prometheus
     resource:
       requests:
         memory: 128Mi
         cpu: 50m
       limits:
         memory: 256Mi
         cpu: 100m
